namespace AudioOptimizer.UI.Localization;

using System.ComponentModel;
using System.Globalization;

/// <summary>
/// UI copy for English and Chinese. English keeps the sentences the render tests look for.
/// Chinese is the wording a person can follow without knowing the internal names.
/// The app starts in Chinese; tests pin English before they render.
/// </summary>
public sealed class UiText : INotifyPropertyChanged
{
    public static UiText Current { get; } = new();

    public static event EventHandler? Changed;

    private static string _culture = "zh";

    public event PropertyChangedEventHandler? PropertyChanged;

    public static bool IsChinese => _culture == "zh";

    public string this[string key] => Get(key);

    public static string Get(string key)
    {
        IReadOnlyDictionary<string, string> table = IsChinese ? Zh : En;
        return table.TryGetValue(key, out string? value) ? value : key;
    }

    public static string Format(string key, params object[] args)
        => string.Format(CultureInfo.InvariantCulture, Get(key), args);

    public static void Use(string culture)
    {
        string next = culture.StartsWith("zh", StringComparison.OrdinalIgnoreCase) ? "zh" : "en";
        if (next == _culture) return;
        _culture = next;
        Current.PropertyChanged?.Invoke(Current, new PropertyChangedEventArgs(null));
        Changed?.Invoke(null, EventArgs.Empty);
    }

    private static readonly Dictionary<string, string> En = new()
    {
        ["App.Purpose"] = "Measure the subwoofers, see where the room is uneven, then get a setting to try.",
        ["Nav.Project"] = "Project",
        ["Nav.Measure"] = "Measure",
        ["Nav.Analysis"] = "Analysis",
        ["Nav.Heatmaps"] = "Heatmaps",
        ["Nav.Optimize"] = "Optimize",
        ["Nav.Wizard"] = "Wizard",
        ["Nav.Simulation"] = "Offline Simulation",
        ["Lang.Chinese"] = "中文",
        ["Lang.English"] = "English",

        ["Project.Title"] = "Open a saved measurement",
        ["Project.Help"] = "Choose the folder you saved last time. You will see which points are done, which failed, and which are still waiting. This does not turn the sound card on.",
        ["Project.Path"] = "Folder",
        ["Project.Load"] = "Open folder",
        ["Project.Foot"] = "Opening a folder only reads session.json. It does not play or record audio.",
        ["Project.Col.Measurement"] = "Measurement",
        ["Project.Col.Mode"] = "Mode",
        ["Project.Col.Position"] = "Position",
        ["Project.Col.State"] = "State",
        ["Project.Col.Signals"] = "Signals",
        ["Project.Col.Peak"] = "Peak",
        ["Project.Col.Reasons"] = "Reasons",
        ["Project.Schema"] = "project {0}",
        ["Project.Sweep"] = "sweep {0}",
        ["Project.Grid"] = "grid {0}",
        ["Project.Id"] = "id {0}",
        ["Project.StatusLine"] = "{0} slots: {1} done, {2} invalid, {3} skipped, {4} pending",
        ["Project.NotLoaded"] = "not loaded ({0})",
        ["Project.NoMissing"] = "no missing or unreadable files",
        ["Project.Affected"] = "{0} file(s) affected: {1}",
        ["Project.None"] = "No project loaded.",
        ["Project.PickFirst"] = "Choose a folder above, then press Open folder.",
        ["Slot.RecordingIr"] = "recording + IR",
        ["Slot.Recording"] = "recording only",
        ["Slot.Ir"] = "IR only",

        ["Measure.Title"] = "Measure the room",
        ["Measure.Help"] = "Choose the microphone and the speaker, start the session, then measure each position with Space or Enter.",
        ["Measure.Input"] = "Microphone",
        ["Measure.Output"] = "Speaker",
        ["Measure.Refresh"] = "Find devices",
        ["Measure.Sweep"] = "Test tone",
        ["Measure.StartHz"] = "Start Hz",
        ["Measure.EndHz"] = "End Hz",
        ["Measure.Seconds"] = "Seconds",
        ["Measure.Rate"] = "Sample rate",
        ["Measure.Grid"] = "Where to put the microphone",
        ["Measure.Width"] = "Width m",
        ["Measure.Depth"] = "Depth m",
        ["Measure.Height"] = "Height m",
        ["Measure.CountX"] = "Points X",
        ["Measure.CountY"] = "Points Y",
        ["Measure.CountZ"] = "Points Z",
        ["Measure.Start"] = "Start or continue",
        ["Measure.Next"] = "Measure this point",
        ["Measure.Skip"] = "Skip this point",
        ["Measure.Abort"] = "Stop",
        ["Measure.SweepLine"] = "sweep: {0}",
        ["Measure.GridLine"] = "grid: {0}",
        ["Flow.NoDeviceList"] = "No device list read yet — press Find devices.",
        ["Flow.NoSession"] = "No session yet. Choose the microphone, the speaker and a folder, then press Start or continue.",
        ["Flow.NoDevices"] = "No audio devices found: connect the measurement microphone and the output device, then refresh.",
        ["Flow.NoInputs"] = "No input devices found ({0} output(s)): the measurement microphone is missing.",
        ["Flow.NoOutputs"] = "No output devices found ({0} input(s)): the playback device is missing.",
        ["Flow.DeviceCounts"] = "{0} input(s), {1} output(s).",
        ["Flow.DeviceListFailed"] = "No device list available: {0}",
        ["Flow.NothingLeft"] = "Nothing left to measure.",
        ["Flow.NoSlot"] = "no slot awaiting measurement",
        ["Flow.NoPoint"] = "no point awaiting measurement",
        ["Flow.Measured"] = "{0} of {1} measured",
        ["Flow.Progress"] = "next slot {0} · grid position {1} · {2}",
        ["Flow.Prompt"] = "Mode {0} · Grid X {1} / Grid Y {2} / Grid Z {3} · X {4} m / Y {5} m / Z {6} m",
        ["Flow.NeedDevices"] = "Select an input (microphone) and an output (playback) device first.",
        ["Flow.NeedSession"] = "Nothing to measure — start or resume a session first.",
        ["Flow.SessionOpen"] = "Session open in '{0}': {1}.",
        ["Flow.Adopted"] = "Project settings adopted from '{0}': press Start or continue to continue its {1} slots.",

        ["Analysis.Title"] = "See the curves",
        ["Analysis.Help"] = "These curves come from the points you measured. The numbers are relative to the line on the plot, not a calibrated loudness.",
        ["Analysis.Mode"] = "Which pass",
        ["Analysis.All"] = "All measured positions",
        ["Analysis.Interp"] = "Interpolate",
        ["Analysis.None"] = "Start or resume a session to analyse measured points.",
        ["Analysis.EmptyMode"] = "No measured points in mode {0} yet — measure a point, or pick another configuration.",

        ["Heat.Title"] = "See the loud and quiet spots",
        ["Heat.Help"] = "Each picture is one height in the room. They share one colour scale, so a brighter colour is always louder.",
        ["Heat.Frequency"] = "Frequency",
        ["Heat.None"] = "Start or resume a session to map measured levels.",

        ["Opt.Title"] = "Suggest a subwoofer setting",
        ["Opt.Help"] = "The four numbers say what you care about more: evenness, the spread between quiet and loud spots, sharp peaks, and deep dips. Max boost is only 0, 3 or 6 dB.",
        ["Opt.Spread"] = "Evenness",
        ["Opt.SpreadHint"] = "How similar the seats should sound",
        ["Opt.P90"] = "Quiet vs loud",
        ["Opt.Peak"] = "Peaks",
        ["Opt.Null"] = "Dips",
        ["Opt.Boost"] = "Max boost (dB)",
        ["Opt.Run"] = "Run search",
        ["Opt.Check"] = "Check the model",
        ["Opt.Diagnosis"] = "What each frequency is doing",
        ["Opt.Causes"] = "Structured causes (§21)",
        ["Opt.Idle"] = "Measure sub A and sub B at the same spots, then run the search.",
        ["Opt.NeedPair"] = "The search needs both A and B measured on the same positions.",
        ["Opt.Ready"] = "{0} position(s) ready; limit {1} dB.",
        ["Opt.Searching"] = "Searching…",
        ["Opt.NoCause"] = "no structured cause reported",
        ["Opt.ModelIdle"] = "The model check has not run.",

        ["Sim.Title"] = "Offline simulation",
        ["Sim.Help"] = "Try the measurement on a made-up rectangular room before you set up a microphone. The app runs the same maths it uses on a real recording. Nothing plays and nothing is recorded.",
        ["Sim.Scenario"] = "Example room",
        ["Sim.Generate"] = "Generate simulation",
        ["Sim.Room"] = "Room size and the area you listen in (metres)",
        ["Sim.Length"] = "Length",
        ["Sim.Width"] = "Width",
        ["Sim.Height"] = "Height",
        ["Sim.Grid"] = "Listening area",
        ["Sim.Subs"] = "Where the two subwoofers sit (metres)",
        ["Sim.SubA"] = "Sub A",
        ["Sim.SubB"] = "Sub B",
        ["Sim.Tone"] = "Test tone, noise, and the frequency to draw",
        ["Sim.Noise"] = "Noise",
        ["Sim.PlaneHz"] = "Map Hz",
        ["Sim.Idle"] = "Pick a scenario and press Generate simulation. Nothing is measured and no audio device is opened.",

        ["Wizard.Done"] = "done",
        ["Wizard.Next"] = "next",
        ["Wizard.Upcoming"] = "upcoming",
        ["Wizard.Guide"] = "Step {0} of {1}: {2} — {3}",
        ["Wizard.GuideDone"] = "All {0} steps are done: the project has a measured grid and an optimisation result.",
        ["Wizard.Input"] = "Input device",
        ["Wizard.Output"] = "Output device",
        ["Wizard.Rate"] = "Sample rate",
        ["Wizard.Sweep"] = "Sweep settings",
        ["Wizard.Area"] = "Measurement area",
        ["Wizard.Points"] = "Generate points",
        ["Wizard.SubA"] = "Sub A",
        ["Wizard.SubB"] = "Sub B",
        ["Wizard.SubAb"] = "Sub A+B",
        ["Wizard.Analysis"] = "Analysis",
        ["Wizard.Optimize"] = "Optimize",
        ["Wizard.Results"] = "Results",
        ["Wizard.InputDetail"] = "selected: {0}",
        ["Wizard.NoneSelected"] = "none selected",
        ["Wizard.InputCue"] = "On Measure, press Find devices, then choose the microphone.",
        ["Wizard.OutputCue"] = "Choose the device that plays into the subwoofers.",
        ["Wizard.RateCue"] = "Set it on Measure. It has to match the rate the devices are using.",
        ["Wizard.SweepCue"] = "20–150 Hz for 1 second is the usual start. Change the band if you need to.",
        ["Wizard.AreaCue"] = "The part of the room the microphone grid covers, in metres.",
        ["Wizard.PointsCue"] = "Press Start or continue. One row is created for every position and every sub combination.",
        ["Wizard.SubACue"] = "Stand where the screen says and press Space or Enter. The order is sub A, then B, then both.",
        ["Wizard.SubBCue"] = "The same positions, with only sub B playing.",
        ["Wizard.SubAbCue"] = "Both subs together. The suggestion is checked against this pass.",
        ["Wizard.AnalysisCue"] = "The Analysis tab draws level, spread and overlay from the points you measured.",
        ["Wizard.NoPair"] = "no point has both A and B measured yet",
        ["Wizard.Paired"] = "{0} of {1} points have A and B measured",
        ["Wizard.OptimizeCue"] = "Press Run search on the Optimize tab.",
        ["Wizard.NoResult"] = "no optimisation run yet",
        ["Wizard.ResultsCue"] = "The suggested setting, the limit it hit, and the reasons are on the Optimize tab.",
        ["Wizard.NoSession"] = "no session yet",
        ["Wizard.ModeDetail"] = "{0} of {1} measured",
        ["Wizard.ModeSkipped"] = "{0} of {1} measured, {2} skipped",

        ["Flow.Skipped"] = "Skipped grid position {0} ({1}). Now: {2}.",
        ["Flow.OpenFailed"] = "Could not open a session in '{0}': {1}",
        ["Flow.NotMeasured"] = "'{0}' was not measured: {1} ({2}, device '{3}'). The point is still {4}.",
        ["Flow.Failed"] = "'{0}' failed: {1}: {2}",
        ["Flow.AbortKeep"] = "grid position {0} keeps its recorded {1} verdict ({2})",
        ["Flow.AbortStill"] = "grid position {0} is still {1}, because no measurement was kept for it",
        ["Flow.AbortDone"] = "every slot already holds a verdict",
        ["Flow.AbortStatus"] = "Run aborted — {0}. Nothing was advanced.",
        ["Flow.AbortKept"] = "Run aborted — the capture for '{0}' at grid position {1} was kept but is recorded Invalid (aborted by you), so it is not measured: re-measure or skip it.",
        ["Flow.RejectedStatus"] = "Grid position {0} ({1}) measured and rejected: {2}.",
        ["Flow.Recorded"] = "{0} recorded as {1}. {2}.",
        ["Flow.SweepBad"] = "Sweep settings are not usable: {0}",
        ["Flow.GridBad"] = "Grid dimensions are not usable: {0}",
        ["Flow.NeedFolder"] = "Type the project directory first: a defaulted path is how a session's WAVs end up in the repository.",
        ["Flow.FeedbackAbort"] = "Aborted by you at grid position {0} ({1}) — re-measure or skip it. Recorded reasons: {2}.",
        ["Flow.FeedbackReject"] = "Rejected at grid position {0} ({1}): {2}. Retry, skip or abort.",
        ["Flow.NoReasons"] = "(no reasons recorded)",

        ["Heat.NoPoints"] = "No measured points yet — measure a point, then map its level.",
        ["Heat.FreqExact"] = "requested {0:F1} Hz → analysis bin {1:F4} Hz (exact)",
        ["Heat.FreqNear"] = "requested {0:F1} Hz → analysis bin {1:F4} Hz (nearest of {2} bins)",
        ["Heat.Plane"] = "Measured level at height Z {0:F2} m, {1:F2} Hz",
        ["Heat.Width"] = "width (m)",
        ["Heat.Depth"] = "depth (m)",
        ["Heat.MapTitle"] = "Level by frequency and position",
        ["Heat.FreqAxis"] = "frequency (Hz)",
        ["Heat.PosAxis"] = "position (measured point)",
        ["Heat.Summary"] = "{0} measured point(s) over {1} height(s); requested band {2}, {3} bins {4:F4}–{5:F4} Hz; scale {6}.",

        ["Analysis.LevelsTitle"] = "Measured levels, mode {0}",
        ["Analysis.SpreadTitle"] = "Spread across positions",
        ["Analysis.RangeTitle"] = "Max − min across positions",
        ["Analysis.OverlayTitle"] = "Before / after",
        ["Analysis.Predicted"] = "predicted, gain 0.0 dB, polarity +1, delay 0.00 ms",
        ["Analysis.NeedBoth"] = " The overlay needs both A and B measured on the same positions.",
        ["Analysis.OverlayNote"] = " The overlay compares measured A with the model's A+B at the identity setting ({0} position(s)).",
        ["Analysis.Summary"] = "{0} measured position(s), mode {1}: mean ±1σ by default, worst σ {2:F2} dB, worst max − min {3:F2} dB.{4}",

        ["Opt.Refused"] = "Max boost is offered as {0} dB only; {1} dB was refused and the limit stays {2} dB.",
        ["Opt.ModelReady"] = "The model check is ready to run against the measured A+B pass.",
        ["Opt.ModelNeed"] = "The model check needs a measured A+B pass as well as A and B.",
        ["Opt.ModelAgrees"] = "The model describes this rig: within {0} dB and {1}° at the compared band (verdict {2}).",
        ["Opt.ModelDisagrees"] = "The model does not describe this rig: verdict {0}, band error {1} dB, spread {2} dB. Check the structured causes below before trusting a predicted optimum.",
        ["Opt.ModelFailed"] = "The model check failed: {0}: {1}",
        ["Opt.SearchFailed"] = "The search failed: {0}: {1}",
        ["Opt.Improved"] = "Improved: score {0} → {1} dB ({2} dB); uniformity {3} → {4} dB standard deviation across positions.",
        ["Opt.Negligible"] = "Not worth changing: the best legal setting improves the score by only {0} dB, below the {1} dB threshold.",
        ["Opt.NoSetting"] = "Not optimizable within the limit: every setting that improves uniformity needs more boost than the {0} dB allowed. The per-frequency rows below say where.",
        ["Opt.Verdict"] = "Verdict: {0}.",
        ["Opt.Recommended"] = "Recommended: gain {0} dB, phase {1}°, polarity {2}, delay {3} ms",
        ["Opt.RecommendedNone"] = "Recommended: none — no legal setting is being proposed.",
        ["Opt.BoostAchieved"] = "Requested limit {0} dB; achieved boost {1} dB (the least any compared position gets is {2} dB).",
        ["Opt.BoostNone"] = "Requested limit {0} dB; no boost was achieved because no setting was proposed.",
        ["Opt.Bound"] = "The limit bound the search: {0} of {1} candidates were rejected as illegal.",
        ["Opt.Unbound"] = "The limit did not bind: none of the {0} candidates was rejected.",
        ["Opt.NoDiagnosis"] = "no per-frequency diagnosis",
        ["Opt.Row"] = "{0} Hz: {1} → {2} dB spread ({3} dB){4}",
        ["Opt.Dominated"] = " — dominated by one or two positions",
        ["Opt.SearchDone"] = "Search complete: {0} candidates, {1} rejected.",
        ["Opt.Safety"] = " Product-safety mode enforced {0} dB (requested {1} dB).",
        ["Opt.Cause.Polarity"] = "polarity: the measured A+B looks inverted relative to the model — check the polarity of one sub",
        ["Opt.Cause.Gain"] = "gain: the compared band is offset by a constant level — check the gain applied to each path",
        ["Opt.Cause.Phase"] = "phase: a phase offset that is not a polarity flip — check the phase setting that was applied",
        ["Opt.Cause.Dsp"] = "device DSP: the error varies with frequency — check EQ, crossover or delay on one path",
        ["Opt.Cause.Sync"] = "measurement sync: a material disagreement with none of the structured causes — check that A, B and A+B were captured in the same session",
        ["Opt.Cause.Unknown"] = "unrecognised cause ({0}): the engine reported a cause this panel does not describe",

        ["Sim.Running"] = "Simulating…",
        ["Sim.Failed"] = "Simulation failed: {0}",
        ["Sim.NoSearch"] = "No search has run.",
        ["Sim.NoTruth"] = "This scenario declares no known correction.",
        ["Sim.NoTruthSearch"] = "This scenario declares no known correction — the search's own before/after above is the whole answer.",
        ["Sim.Known"] = "known correction {0}; the optimizer never saw it.{1}",
        ["Sim.Reaches"] = " It reaches {0}.",
        ["Sim.Pipeline"] = "{0} points measured through the shipped chain — {1}",
        ["Sim.Done"] = "Done: {0} measurements, {1} bins inside {2}.",
        ["Sim.Verdict"] = " Search verdict: {0}.",
    };

    private static readonly Dictionary<string, string> Zh = new()
    {
        ["App.Purpose"] = "先把低音炮测一遍，看房间里哪里响、哪里闷，再给出一个可以试的设置。",
        ["Nav.Project"] = "项目",
        ["Nav.Measure"] = "测量",
        ["Nav.Analysis"] = "曲线",
        ["Nav.Heatmaps"] = "分布",
        ["Nav.Optimize"] = "建议",
        ["Nav.Wizard"] = "步骤",
        ["Nav.Simulation"] = "模拟",
        ["Lang.Chinese"] = "中文",
        ["Lang.English"] = "English",

        ["Project.Title"] = "打开以前的测量",
        ["Project.Help"] = "选中上次保存的文件夹。这里会告诉你哪些点测完了、哪些没通过、哪些还没测。这一步不会打开声卡。",
        ["Project.Path"] = "文件夹",
        ["Project.Load"] = "打开文件夹",
        ["Project.Foot"] = "打开文件夹只是读取里面的 session.json，不会出声，也不会录音。",
        ["Project.Col.Measurement"] = "测点",
        ["Project.Col.Mode"] = "组合",
        ["Project.Col.Position"] = "位置",
        ["Project.Col.State"] = "状态",
        ["Project.Col.Signals"] = "文件",
        ["Project.Col.Peak"] = "峰值",
        ["Project.Col.Reasons"] = "原因",
        ["Project.Schema"] = "项目格式 {0}",
        ["Project.Sweep"] = "测试音 {0}",
        ["Project.Grid"] = "测点网格 {0}",
        ["Project.Id"] = "编号 {0}",
        ["Project.StatusLine"] = "共 {0} 条记录：{1} 条完成，{2} 条无效，{3} 条跳过，{4} 条还没测",
        ["Project.NotLoaded"] = "没有打开（{0}）",
        ["Project.NoMissing"] = "没有缺失或读不出的文件",
        ["Project.Affected"] = "有 {0} 个文件有问题：{1}",
        ["Project.None"] = "打开之后，下面会列出每个测点。",
        ["Project.PickFirst"] = "先在上面填好文件夹，再点「打开文件夹」。",
        ["Slot.RecordingIr"] = "录音和脉冲都在",
        ["Slot.Recording"] = "只有录音",
        ["Slot.Ir"] = "只有脉冲",

        ["Measure.Title"] = "开始测量",
        ["Measure.Help"] = "先选麦克风和音箱，再点「开始或继续」。然后站到屏幕提示的位置，按空格或回车测这一个点。",
        ["Measure.Input"] = "麦克风",
        ["Measure.Output"] = "音箱",
        ["Measure.Refresh"] = "查找设备",
        ["Measure.Sweep"] = "测试音",
        ["Measure.StartHz"] = "起始频率 Hz",
        ["Measure.EndHz"] = "结束频率 Hz",
        ["Measure.Seconds"] = "时长（秒）",
        ["Measure.Rate"] = "采样率",
        ["Measure.Grid"] = "麦克风要放的范围",
        ["Measure.Width"] = "宽（米）",
        ["Measure.Depth"] = "深（米）",
        ["Measure.Height"] = "高（米）",
        ["Measure.CountX"] = "横向几个点",
        ["Measure.CountY"] = "纵向几个点",
        ["Measure.CountZ"] = "高度几层",
        ["Measure.Start"] = "开始或继续",
        ["Measure.Next"] = "测量这个点",
        ["Measure.Skip"] = "跳过这个点",
        ["Measure.Abort"] = "停止",
        ["Measure.SweepLine"] = "测试音：{0}",
        ["Measure.GridLine"] = "网格：{0}",
        ["Flow.NoDeviceList"] = "还没有设备列表。先点「查找设备」。",
        ["Flow.NoSession"] = "还没开始。先选麦克风、音箱和保存文件夹，再点「开始或继续」。",
        ["Flow.NoDevices"] = "没有找到音频设备。接上测量麦克风和播放设备后，再点查找设备。",
        ["Flow.NoInputs"] = "没有找到麦克风（播放设备有 {0} 个）。",
        ["Flow.NoOutputs"] = "没有找到播放设备（麦克风有 {0} 个）。",
        ["Flow.DeviceCounts"] = "找到 {0} 个麦克风，{1} 个播放设备。",
        ["Flow.DeviceListFailed"] = "读设备列表失败：{0}",
        ["Flow.NothingLeft"] = "该测的点都测完了。",
        ["Flow.NoSlot"] = "没有待测记录",
        ["Flow.NoPoint"] = "没有待测位置",
        ["Flow.Measured"] = "已完成 {0} / {1}",
        ["Flow.Progress"] = "下一条是 {0}，位置 {1}，{2}",
        ["Flow.Prompt"] = "现在测 {0}。请把麦克风放到 X {4} 米、Y {5} 米、Z {6} 米（网格 X {1} / Y {2} / Z {3}）。",
        ["Flow.NeedDevices"] = "请先选择麦克风和播放设备。",
        ["Flow.NeedSession"] = "还不能测。请先点「开始或继续」。",
        ["Flow.SessionOpen"] = "已在「{0}」打开测量：{1}。",
        ["Flow.Adopted"] = "已采用「{0}」里的设置。点「开始或继续」接着测剩下的 {1} 条。",

        ["Analysis.Title"] = "看曲线",
        ["Analysis.Help"] = "这些曲线来自你测到的点。纵轴是相对图上那条参考线的差别，不是已经校准过的绝对响度。",
        ["Analysis.Mode"] = "哪一次",
        ["Analysis.All"] = "画出所有已测位置",
        ["Analysis.Interp"] = "把点连顺",
        ["Analysis.None"] = "先开始或继续一次测量，才能看曲线。",
        ["Analysis.EmptyMode"] = "「{0}」这一组还没有测完的点。先测一个点，或换一组看。",

        ["Heat.Title"] = "看哪里响、哪里闷",
        ["Heat.Help"] = "每一张图是房间里的一个高度。颜色用同一把尺子，所以更亮就一定是更响。",
        ["Heat.Frequency"] = "频率",
        ["Heat.None"] = "先开始或继续一次测量，才能看分布。",

        ["Opt.Title"] = "给出低音炮设置",
        ["Opt.Help"] = "这四个数字是你更在意什么：座位之间是否接近、最响和最闷差多少、尖峰、还有凹陷。提升上限只能选 0、3 或 6 dB。",
        ["Opt.Spread"] = "均匀",
        ["Opt.SpreadHint"] = "各个座位听起来有多接近",
        ["Opt.P90"] = "响和闷",
        ["Opt.Peak"] = "尖峰",
        ["Opt.Null"] = "凹陷",
        ["Opt.Boost"] = "最大提升 (dB)",
        ["Opt.Run"] = "开始寻找",
        ["Opt.Check"] = "检查模型是否靠谱",
        ["Opt.Diagnosis"] = "每个频率的情况",
        ["Opt.Causes"] = "具体原因",
        ["Opt.Idle"] = "先在同样的位置测完低音炮 A 和 B，再来寻找设置。",
        ["Opt.NeedPair"] = "同一个位置上，A 和 B 都测完才能寻找设置。",
        ["Opt.Ready"] = "有 {0} 个位置可以用；提升上限 {1} dB。",
        ["Opt.Searching"] = "正在寻找…",
        ["Opt.NoCause"] = "没有列出具体原因",
        ["Opt.ModelIdle"] = "还没有检查模型。",

        ["Sim.Title"] = "先模拟一次",
        ["Sim.Help"] = "还没摆麦克风之前，可以先用一个假想的长方形房间走一遍测量。用的是和真录音同一套计算。不会出声，也不会录音。",
        ["Sim.Scenario"] = "例子",
        ["Sim.Generate"] = "生成模拟",
        ["Sim.Room"] = "房间尺寸，以及你坐的那一块（米）",
        ["Sim.Length"] = "长",
        ["Sim.Width"] = "宽",
        ["Sim.Height"] = "高",
        ["Sim.Grid"] = "听音区域",
        ["Sim.Subs"] = "两只低音炮放在哪里（米）",
        ["Sim.SubA"] = "低音炮 A",
        ["Sim.SubB"] = "低音炮 B",
        ["Sim.Tone"] = "测试音、噪声，以及要画的频率",
        ["Sim.Noise"] = "噪声",
        ["Sim.PlaneHz"] = "图的频率",
        ["Sim.Idle"] = "选一个例子，然后点「生成模拟」。不会真正测量，也不会打开声卡。",

        ["Wizard.Done"] = "完成",
        ["Wizard.Next"] = "现在做",
        ["Wizard.Upcoming"] = "还没到",
        ["Wizard.Guide"] = "第 {0} 步，共 {1} 步：{2}。{3}",
        ["Wizard.GuideDone"] = "{0} 步都做完了：房间测过了，也已经有一个建议设置。",
        ["Wizard.Input"] = "选择麦克风",
        ["Wizard.Output"] = "选择音箱",
        ["Wizard.Rate"] = "采样率",
        ["Wizard.Sweep"] = "测试音",
        ["Wizard.Area"] = "测量范围",
        ["Wizard.Points"] = "生成测点",
        ["Wizard.SubA"] = "只开低音炮 A",
        ["Wizard.SubB"] = "只开低音炮 B",
        ["Wizard.SubAb"] = "两只一起",
        ["Wizard.Analysis"] = "看曲线",
        ["Wizard.Optimize"] = "找设置",
        ["Wizard.Results"] = "看结果",
        ["Wizard.InputDetail"] = "已选：{0}",
        ["Wizard.NoneSelected"] = "还没选",
        ["Wizard.InputCue"] = "到「测量」页点「查找设备」，然后选测量麦克风。",
        ["Wizard.OutputCue"] = "选低音炮所接的那台播放设备。",
        ["Wizard.RateCue"] = "在测量页填写，要和声卡正在用的采样率一样。",
        ["Wizard.SweepCue"] = "一般从 20–150 Hz、1 秒开始。需要别的频段就改这里。",
        ["Wizard.AreaCue"] = "麦克风网格覆盖的房间范围，单位是米。",
        ["Wizard.PointsCue"] = "点「开始或继续」。每个位置、每种低音炮组合都会有一条待测记录。",
        ["Wizard.SubACue"] = "站到屏幕写的位置，按空格或回车。顺序是先 A，再 B，再两只一起。",
        ["Wizard.SubBCue"] = "同样的位置，只让低音炮 B 出声。",
        ["Wizard.SubAbCue"] = "两只一起出声。建议设置会和这一次对照。",
        ["Wizard.AnalysisCue"] = "「曲线」页用测到的点画出响度、均匀程度和对比。",
        ["Wizard.NoPair"] = "还没有哪个位置把 A 和 B 都测完",
        ["Wizard.Paired"] = "{1} 个位置里，有 {0} 个已经测完 A 和 B",
        ["Wizard.OptimizeCue"] = "到「建议」页点「开始寻找」。",
        ["Wizard.NoResult"] = "还没有跑过建议",
        ["Wizard.ResultsCue"] = "建议的设置、碰到的限制和原因都在「建议」页。",
        ["Wizard.NoSession"] = "还没开始测量",
        ["Wizard.ModeDetail"] = "已测 {0} / {1}",
        ["Wizard.ModeSkipped"] = "已测 {0} / {1}，跳过 {2}",

        ["Flow.Skipped"] = "已跳过位置 {0}（{1}）。接下来：{2}。",
        ["Flow.OpenFailed"] = "打不开「{0}」里的测量：{1}",
        ["Flow.NotMeasured"] = "「{0}」没有测成：{1}（{2}，设备「{3}」）。这个点仍是 {4}。",
        ["Flow.Failed"] = "「{0}」失败了：{1}：{2}",
        ["Flow.AbortKeep"] = "位置 {0} 仍保留已记下的结果 {1}（{2}）",
        ["Flow.AbortStill"] = "位置 {0} 仍是 {1}，因为这次没有留下录音",
        ["Flow.AbortDone"] = "每个点都已经有结果了",
        ["Flow.AbortStatus"] = "已停止。{0}。进度没有往前走。",
        ["Flow.AbortKept"] = "已停止。「{0}」在位置 {1} 的录音留下了，但记成无效（你中途停的），不算测完。可以重测，也可以跳过。",
        ["Flow.RejectedStatus"] = "位置 {0}（{1}）测完了，但没通过：{2}。",
        ["Flow.Recorded"] = "「{0}」已记为 {1}。{2}",
        ["Flow.SweepBad"] = "测试音的设置不能用：{0}",
        ["Flow.GridBad"] = "网格尺寸不能用：{0}",
        ["Flow.NeedFolder"] = "先填写保存文件夹。不填的话，录音会写到程序所在的目录里。",
        ["Flow.FeedbackAbort"] = "你在位置 {0}（{1}）中途停了。可以重测，也可以跳过。记下的原因：{2}。",
        ["Flow.FeedbackReject"] = "位置 {0}（{1}）没通过：{2}。可以重测、跳过，或停止。",
        ["Flow.NoReasons"] = "（没有记下原因）",

        ["Heat.NoPoints"] = "还没有测完的点。先测一个点，再回来看哪里响、哪里闷。",
        ["Heat.FreqExact"] = "你选的是 {0:F1} Hz，正好落在分析频点 {1:F4} Hz。",
        ["Heat.FreqNear"] = "你选的是 {0:F1} Hz，最接近的分析频点是 {1:F4} Hz（{2} 个频点里最近的一个）。",
        ["Heat.Plane"] = "高度 {0:F2} 米、{1:F2} Hz 的响度",
        ["Heat.Width"] = "宽（米）",
        ["Heat.Depth"] = "深（米）",
        ["Heat.MapTitle"] = "每个位置、每个频率的响度",
        ["Heat.FreqAxis"] = "频率（Hz）",
        ["Heat.PosAxis"] = "位置（测点）",
        ["Heat.Summary"] = "测了 {0} 个点，共 {1} 个高度。要看的频段是 {2}，里面有 {3} 个频点（{4:F4}–{5:F4} Hz）。颜色尺子：{6}。",

        ["Analysis.LevelsTitle"] = "{0} 这一组测到的响度",
        ["Analysis.SpreadTitle"] = "各个位置差多少",
        ["Analysis.RangeTitle"] = "最响和最闷差多少",
        ["Analysis.OverlayTitle"] = "改之前 / 改之后",
        ["Analysis.Predicted"] = "按模型算的，增益 0.0 dB，极性 +1，延迟 0.00 毫秒",
        ["Analysis.NeedBoth"] = " 要看对比，同一个位置得把低音炮 A 和 B 都测完。",
        ["Analysis.OverlayNote"] = " 对比的是测到的 A，和「先不改任何设置」时模型算出的 A+B（{0} 个位置）。",
        ["Analysis.Summary"] = "{1} 这组测了 {0} 个位置。默认画的是平均和上下浮动。差别最大的时候，标准差 {2:F2} dB，最响和最闷相差 {3:F2} dB。{4}",

        ["Opt.Refused"] = "提升只能选 {0} dB。{1} dB 没有采用，上限仍是 {2} dB。",
        ["Opt.ModelReady"] = "两只一起的那一次也测过了，可以检查模型是否靠谱。",
        ["Opt.ModelNeed"] = "要检查模型，还得把两只一起的那一次也测完。",
        ["Opt.ModelAgrees"] = "模型和这次实测对得上：比较的频段里，误差在 {0} dB、{1}° 以内（结论 {2}）。",
        ["Opt.ModelDisagrees"] = "模型和这次实测对不上。结论是 {0}，频段误差 {1} dB，偏差散开 {2} dB。先看下面的原因，再决定要不要相信算出来的设置。",
        ["Opt.ModelFailed"] = "模型检查失败了：{0}：{1}",
        ["Opt.SearchFailed"] = "寻找失败了：{0}：{1}",
        ["Opt.Improved"] = "有改善。分数从 {0} 到 {1} dB（变化 {2} dB）。各位置的差异从 {3} 到 {4} dB。",
        ["Opt.Negligible"] = "不值得改。没超限的设置里，最好的也只让分数好 {0} dB，低于 {1} dB 这条线。",
        ["Opt.NoSetting"] = "在 {0} dB 的提升上限里找不到更好的设置。想让各位置更接近，就得超过这个上限。下面按频率写了差在哪里。",
        ["Opt.Verdict"] = "结论：{0}。",
        ["Opt.Recommended"] = "建议：增益 {0} dB，相位 {1}°，极性 {2}，延迟 {3} 毫秒",
        ["Opt.RecommendedNone"] = "没有建议。现在没有一个不超限的设置可以给你。",
        ["Opt.BoostAchieved"] = "你要求的上限是 {0} dB；实际提升 {1} dB（各位置里最少的是 {2} dB）。",
        ["Opt.BoostNone"] = "你要求的上限是 {0} dB。没有给出设置，所以也没有提升。",
        ["Opt.Bound"] = "上限卡住了这次寻找：{1} 个候选里有 {0} 个因为超限被丢掉。",
        ["Opt.Unbound"] = "上限没有卡住：{0} 个候选都没有因为超限被丢掉。",
        ["Opt.NoDiagnosis"] = "没有按频率的说明",
        ["Opt.Row"] = "{0} Hz：差异从 {1} 到 {2} dB（变化 {3} dB）{4}",
        ["Opt.Dominated"] = "，主要是一两个位置造成的",
        ["Opt.SearchDone"] = "找完了：看了 {0} 个候选，丢掉 {1} 个。",
        ["Opt.Safety"] = " 为了安全，实际用的上限是 {0} dB（你填的是 {1} dB）。",
        ["Opt.Cause.Polarity"] = "极性反了：测到的两只一起，和模型比起来是反相的。检查其中一只低音炮的正负极。",
        ["Opt.Cause.Gain"] = "增益差一截：整段响度差一个固定的数。检查每只低音炮的增益。",
        ["Opt.Cause.Phase"] = "相位偏了：不是简单的正负接反。检查相位旋钮。",
        ["Opt.Cause.Dsp"] = "设备自己做了处理：误差随频率变。检查均衡、分频或延迟。",
        ["Opt.Cause.Sync"] = "几次测量对不上：没有对上上面这些原因。确认 A、B 和两只一起是同一次摆放测的。",
        ["Opt.Cause.Unknown"] = "出现了这里不认识的原因（{0}）。",

        ["Sim.Running"] = "正在模拟…",
        ["Sim.Failed"] = "模拟失败：{0}",
        ["Sim.NoSearch"] = "还没有寻找设置。",
        ["Sim.NoTruth"] = "这个例子没有事先写好的正确答案。",
        ["Sim.NoTruthSearch"] = "这个例子没有事先写好的正确答案。上面寻找前后的对比就是全部结果。",
        ["Sim.Known"] = "事先写好的正确答案是 {0}。寻找的时候并没有拿它当答案。{1}",
        ["Sim.Reaches"] = " 用这个正确答案，统计是 {0}。",
        ["Sim.Pipeline"] = "走完正式测量流程，共 {0} 个点 — {1}",
        ["Sim.Done"] = "模拟完成：{0} 次测量，频段 {2} 里有 {1} 个频点。",
        ["Sim.Verdict"] = " 寻找结论：{0}。",
        ["Sim.Title.single-sub"] = "S1 一只低音炮，只算直达声",
        ["Sim.Title.two-sub"] = "S2 两只低音炮，27 个麦克风",
        ["Sim.Title.modal-room"] = "S3 带反射的房间，40–100 Hz",
        ["Sim.Title.dual-sub"] = "S4 低音炮摆错了，自己找设置",
        ["Sim.Title.deep-null"] = "S5 50 Hz 有一个深坑",
        ["Sim.single-sub"] = "single-sub：一只低音炮、一只麦克风，只算直达声。用来核对距离、延迟和相位。",
        ["Sim.two-sub"] = "two-sub：两只低音炮、27 个麦克风。看两只加在一起时的干涉。",
        ["Sim.modal-room"] = "modal-room：角落一只低音炮，带房间反射，看 40–100 Hz 哪里响、哪里闷。",
        ["Sim.dual-sub"] = "dual-sub：低音炮 B 故意摆错了。程序只能根据测量自己找一个更均匀的设置。",
        ["Sim.deep-null"] = "deep-null：两只低音炮几乎对消，50 Hz 有一个深坑。看程序会不会用增益去填这个坑。",
    };
}
